Первая реализация ТЗ спринт 7.
griatva/java-kanban pull request #2
Opened 2024-06-02 15:57 UTC by griatva

2024-06-03 07:53 UTC, TomattmanYandex requested changes
Привет, есть моменты которые надо доделать/переделать

2024-06-03 07:53 UTC, TomattmanYandex commented on src/manager/task/InMemoryTaskManager.java
> +    public int getCounterId() {
стоит сделать его приватным или протектед

2024-06-03 07:53 UTC, TomattmanYandex commented on src/manager/task/FileBackedTaskManager.java
> +        super(historyManager);
а считать данные из файла

2024-06-03 07:53 UTC, TomattmanYandex commented on src/manager/task/FileBackedTaskManager.java
> +                bw.write(toString(entry.getValue()));
я бы порекомендовал иметь класс конвертер который умет превращать таск и другие  штуки в строку и обратно так было бы лучше и проще в некоторых реализациях

2024-06-03 07:53 UTC, TomattmanYandex commented on src/model/Task.java
> +    private Integer epicId;
откуда у таска взялся id эпика?
убрать отсюда

2024-06-03 07:53 UTC, TomattmanYandex commented on src/manager/task/FileBackedTaskManager.java
> +        return task.getId() + "," + task.getType() + "," + task.getName() + "," + task.getStatus() + "," +
откуда у таска взялся id эпика? такие штуки решаются через перегрузку методов

2024-06-03 07:53 UTC, TomattmanYandex commented on src/manager/task/FileBackedTaskManager.java
> +                        Epic tiedEpic = manager.epics.get(subTask.getEpicId());
если таск считается раньше чем эпик, то привязки не произойдёт, следует это сделать отдельным циклом

2024-06-03 09:22 UTC, griatva commented on src/manager/task/FileBackedTaskManager.java
> +        super(historyManager);
Мне не совсем понятен этот комментарий. На следующей (18-ой) строке я инициализирую переменную file. Или имеется что-то другое в виду? Плюс есть еще один конструктор, где file передается как аргумент.

2024-06-03 10:28 UTC, griatva commented on src/manager/task/InMemoryTaskManager.java
> +    public int getCounterId() {
Я его сделала паблик, чтобы можно было проверять изменения этого счетчика в тестах, иначе я не понимаю, как мне его не достать и проверить, что он изменился. Я этот метод и создала, собственно, для тестов.. Может быть, вы мне можете подсказать, как тогда лучше сделать?

2024-06-03 12:27 UTC, griatva commented on src/manager/task/FileBackedTaskManager.java
> +        return task.getId() + "," + task.getType() + "," + task.getName() + "," + task.getStatus() + "," +
Я убрала поле epicId из таска и оставила только методы getType() и getEpicId(), которые нужны для сборки строки из задачи в методе toString(Task task). Как я понимаю, по ООП правильно, если метод toString(Task task) будет универсальный для всех типов задач и если в нем не будет ветвлений по типам. Для этого я оставляю методы getType() и getEpicId() в таске. Так корректно?

2024-06-04 08:10 UTC, TomattmanYandex commented on src/manager/task/InMemoryTaskManager.java
> +    public int getCounterId() {
создаешь новый таск смотришь его идентификатор,
не стоит делать методы более видимыми только ради тестов, в обратном порядке иногда стоит, есть тестовые инструменты которые позволяют тестировать закрытые методы

2024-06-04 08:10 UTC, TomattmanYandex commented on src/manager/task/FileBackedTaskManager.java
> +        super(historyManager);
логика примерно такая, когда ты создаешь файловый таск менеджер, ты связываешь его с файлом, и если он существует то с файла должны быть вытянуты данные,
сейчас можно вызвать любой из конструкторов и данные не будут считаны
за то потом будут переписаны
выхода два
1) вызываем метод считывания файла в конструкторе (но так как есть статический метод второй варинат будет лучше)
2) у нас есть статический метод который считывает из файла, можем позволить создавать обьект только через него, для этого делаем конструкторы приватными (они будут видны из метода, но снаружи нет)

2024-06-04 08:10 UTC, TomattmanYandex commented on src/manager/task/FileBackedTaskManager.java
> +        super(historyManager);
P.S. конструкторы можно реализовать еще интереснее
конструктор с одним параметром, может вызывать второй конструктор, где второй параметр, будет значение по умолчанию (это удобно когда логика посложнее)

2024-06-04 08:10 UTC, TomattmanYandex commented on src/converter/TaskConverter.java
> +                task.getDescription() + "," + task.getEpicId();
откуда у таска id  эпика

2024-06-04 08:10 UTC, TomattmanYandex commented on src/model/Task.java
> +    public Integer getEpicId() {
то что убрали id эпика значит что и надо убрать методы, которые его проставляют

2024-06-04 08:10 UTC, TomattmanYandex commented on src/model/Task.java
> +    public Integer getEpicId() {
класс не должен создавать какие то методы специально для какого то конкретного наслденика

2024-06-04 08:10 UTC, TomattmanYandex commented on src/manager/task/FileBackedTaskManager.java
> +        return task.getId() + "," + task.getType() + "," + task.getName() + "," + task.getStatus() + "," +
нет,  это ошибка, наследование существует специально для расширения функционала, 
т.е. таск отвечает только за себя, а если надо что то, что работает почти так же как и он, но несет больше функционала, то мы делаем наследника (расширяем его) и наследник имеет тот же функционал + дополнительный (плюс какой то может быть изменен)
и наличие id эпика это расширение, сам таск не должен о нем ничего знать

2024-06-04 08:10 UTC, TomattmanYandex commented on src/manager/task/FileBackedTaskManager.java
> +        return task.getId() + "," + task.getType() + "," + task.getName() + "," + task.getStatus() + "," +
getTaskType относится ко всем типам его можно оставить

2024-06-04 08:11 UTC, TomattmanYandex commented on src/manager/task/FileBackedTaskManager.java
> +        return task.getId() + "," + task.getType() + "," + task.getName() + "," + task.getStatus() + "," +
а для таких случаев существует перегрузка методов
несколько методов с одинаковыми именами, но с разным набором параметров, и виртуальная машина будет использовать тот, который максимально подходит

2024-06-04 08:14 UTC, TomattmanYandex requested changes
Привет, накинул еще коментариев

2024-06-04 08:14 UTC, TomattmanYandex commented on src/manager/task/FileBackedTaskManager.java
> +                for (SubTask subTask : manager.subTasks.values()) {
этот цикл теперь отдельный, но по сути ничего не поменялось, стало даже хуже, потмоу что теперь на каждую строчку будет попытка переписать все эпики

2024-06-04 08:14 UTC, TomattmanYandex commented on src/manager/task/FileBackedTaskManager.java
> +                for (SubTask subTask : manager.subTasks.values()) {
сначала стоит считать ВСЕ таски а потом когда все линии из файла прочитаны, тогда мы понимаем, что все что было в файле, уже в памяти, то надо пройтись по тому что в памяти и привязать друг к другу

2024-06-04 10:44 UTC, griatva commented on src/manager/task/FileBackedTaskManager.java
> +        return task.getId() + "," + task.getType() + "," + task.getName() + "," + task.getStatus() + "," +
Интересно, как по-разному можно интерпретировать принципы ООП)) Наставник нам в вебинаре специально показывал и прямо говорил, что нужен метод getEpicId именно в таске, чтобы все остальные его наследники это дело наследовали, и чтобы потом мы могли одной строчкой в toString(Task task) обработать все типы-наследники таска. Наследников может быть десятки и делать ветвления на каждый из-за одного поля - это прям вот неправильно, не соответствует ООП) Так говорил наставник) Но ваши комментарии мне совершенно понятны, все логично и правильно)) Но я не понимаю, как вот в таких ситуациях понять, что правильнее))

2024-06-06 11:55 UTC, TomattmanYandex approved these changes
Привет, все отлично, кроме одного момента непонятного, но он кажется мелочью

2024-06-06 11:55 UTC, TomattmanYandex commented on src/manager/task/FileBackedTaskManager.java
> +            if (tasks.isEmpty() && subTasks.isEmpty() && epics.isEmpty()) {
Вопрос, а зачем эта ветка?

2024-06-06 12:57 UTC, griatva commented on src/manager/task/FileBackedTaskManager.java
> +            if (tasks.isEmpty() && subTasks.isEmpty() && epics.isEmpty()) {
Я добавила это для тестов, чтобы не переделывать их логику. Перед каждым тестом у меня создается менеджер на основе одного и того же файла. Если до этого теста уже был другой, тогда в файле есть данные и они подгружаются в этот вновь созданный менеджер. Если там были задачи, то вместе с подгрузкой задач у меня восстанавливается значение счетчика id. Задачи из мап я удалить могу методом, а вот обнулить снова счетчик - не могу. Но если сделать такую ветку, то метод save() может отследить, что все задачи удалились, файл чист, поэтому и счетчик можно обнулить. И тогда все тесты корректно работают)

2024-06-16 20:17 UTC, merged