ТЗ-9
griatva/java-kanban pull request #4
Opened 2024-07-09 14:03 UTC by griatva

2024-07-10 07:52 UTC, TomattmanYandex requested changes
Комменты в коде

2024-07-10 07:52 UTC, TomattmanYandex commented on src/converter/DurationAdapter.java
> +            jsonWriter.value("null");
json как формат сам по себе поддерживает null значение, оно без кавычек, с кавычками - это валидная строка

2024-07-10 07:52 UTC, TomattmanYandex commented on src/manager/server/HttpTaskServer.java
> +    Gson gson;
модификаторы доступа

2024-07-10 07:52 UTC, TomattmanYandex commented on src/manager/server/HistoryHandler.java
> +    TaskManager manager;
модификаторы

2024-07-10 07:52 UTC, TomattmanYandex commented on src/manager/server/TaskHandler.java
> +    TaskManager manager;
модификаторы доступа

2024-07-10 07:52 UTC, TomattmanYandex commented on src/manager/server/PrioritizedHandler.java
> +    TaskManager manager;
модификаторы доступа

2024-07-10 07:52 UTC, TomattmanYandex commented on src/manager/server/EpicHandler.java
> +public class EpicHandler extends TaskHandler implements HttpHandler {
очень непонятна очередность наследования, почему наследуются от таск хэндлера все?
почему у эпик хэндлера есть методы hadleGetTask

рекомендация на такой случай
если все же какие то методы общие есть, то сделать абстрактный класс и вынести этот метод туда, остальные сделать абстрактными и дать более нейтральные имена, например getOneEntity getListEnttities
возможно базоый класс стоит завести только для того чтобы хранить таск менеджер, но тогда не стоит в нем создавать методы, и так же от него унаследовать хендлер истории и приоритезированных тасков

ну и еще момент, про енамы с операциями
можно их сделать так как я писал выше, более абстрактно обозвать

2024-07-10 10:40 UTC, griatva commented on src/manager/server/EpicHandler.java
> +public class EpicHandler extends TaskHandler implements HttpHandler {
Переделала: 
1. добавила интерфейс ResponseWriter  и в нем теперь метод writeResponse.
2. класс BaseHttpHandler теперь абстрактный и в нем все повторяющиеся методы с универсальными именами
3. enum откорректирован, теперь там ендпоинты тоже с универсальными названиями
4. все пять хендлеров реализуют интерфейс ResponseWriter, а хендлеры с задачми дополнительно наследуют BaseHttpHandler.

2024-07-10 14:42 UTC, TomattmanYandex requested changes
Еще можно немножко улучшить

2024-07-10 14:42 UTC, TomattmanYandex commented on src/manager/server/EpicHandler.java
> +    protected final TaskManager manager;
можно было бы переменную и конструктор с ней вынести в абстрактный класс

2024-07-10 14:42 UTC, TomattmanYandex commented on src/manager/server/HistoryHandler.java
> +public class HistoryHandler implements HttpHandler, ResponseWriter {
можно было бы так же унаследовать от базового хендлера 
и не имплементировать методы
точнее заимплементировать но с пустым телом

2024-07-11 09:59 UTC, TomattmanYandex approved these changes
Принято

2024-07-11 09:59 UTC, TomattmanYandex commented on src/manager/server/BaseHttpHandler.java
> +public class BaseHttpHandler {
Смотри еще как можно было сделать 
1_ делаем этот класс абстрактным, 
2_ делаем чтобы он имплементил httpHandler
3_ метод handle делаем абстрактным

Готово, в каждом хендлере не надо указывать что он имплементит

2024-07-11 13:11 UTC, merged